#!/bin/bash

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

source $controlfolder/control.txt

get_controls

GAMEDIR=/$directory/godot
LOGS=$GAMEDIR/logs
GAME=${1}

cd $GAMEDIR/bin/

now=$(date +"%m_%d_%H_%M_%S")
driver="opengl3"

# Add the new bin in the bin folder and change FRT to use a different version of godot.
if [[ $GAME == *"/v400/"* ]]; then
# Godot v4.0.3
  FRT="frt_210_403_arm64v8.bin"
  LOG_TXT="$LOGS/v400/log_$now.txt"
elif [[ $GAME == *"/v351/"* ]]; then
# Godot v3.5.1
  FRT="frt_210_351_arm64v8.bin"
  LOG_TXT="$LOGS/v351/log_$now.txt"
else
# Default to Godot v3.5.1
  FRT="frt_210_351_arm64v8.bin"
  LOG_TXT="$LOGS/default/log_$now.txt"
  echo "Defaulted to $FRT" >> $LOG_TXT
fi

echo "Booting up the game: $GAME" >> $LOG_TXT

export FRT_NO_EXIT_SHORTCUTS=true
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export LD_LIBRARY_PATH="$GAMEDIR/lib"

./$FRT -f -v --rendering-driver $driver --main-pack $GAME 2>&1 | tee -a $LOG_TXT

